name: build
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          corepack enable
          pnpm i
          pnpm run init
          cp node_modules/canvaskit-wasm/bin/canvaskit.wasm dist/
          pnpm run build
      - run: pnpm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
