name: build
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          wget https://github.com/qiuxiang/genshin-maps/files/12844845/data.tar.gz
          tar xf data.tar.gz
          mv dist/data_pb.* src/
          cp index.html dist/
          corepack enable
          pnpm i
          cp node_modules/canvaskit-wasm/bin/canvaskit.wasm dist/
          pnpm run build
      - run: pnpm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
